### ISSUE TITLE
About Url

### ISSUE THREAD

**Issue by o-david** [Munyia/Prj1#1]
Great job with your page. However, I noticed the URL in your About is invalid. 

<img width="428" alt="Screenshot 2024-03-12 at 06 06 34" src="https://github.com/Munyia/Coffee-page/assets/30634148/588203b1-f68d-41e5-b7bd-d39684a78055">

**Comment by Munyia** [comment]
Seriously, Mr. Formality using email aiiii it's funny but serious, I will
make the necessary changes and host on vercel, is that perfect?

**Comment by Munyia** [comment]
Thanks a lot for highlighting that, I have fixed it. Please feel free to close this issue when you see it.

**Comment by o-david** [comment]
Its all good 👍

**Comment by Munyia** [comment]
Thanks
